[build]
template = "custom"
script = """
cookbook_cargo_packages service-monitor services gtrand

# rename the executable binaries
mv "${COOKBOOK_STAGE}"/usr/bin/service-monitor_service-monitor "${COOKBOOK_STAGE}"/usr/bin/service-monitor
mv "${COOKBOOK_STAGE}"/usr/bin/service-monitor_services "${COOKBOOK_STAGE}"/usr/bin/services
mv "${COOKBOOK_STAGE}"/usr/bin/service-monitor_gtrand "${COOKBOOK_STAGE}"/usr/bin/gtrand

# place registry in the filesystem
mkdir -pv "${COOKBOOK_STAGE}"/usr/share # create the /usr/share folder inside the package
cp -rv "${COOKBOOK_SOURCE}"/service-monitor/smregistry.toml "${COOKBOOK_STAGE}"/usr/share # copy the configuration file from the program source code to the package

"""
